[build]
  command = "npm run build"
  publish = "dist" # Use "build" for Create React App
# Add CORS headers for all API routes
[[headers]]
  for = "/api/"
  [headers.values]
    Access-Control-Allow-Origin = ""
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
# Rule 1: For ConceptMap APIs
[[redirects]]
  from = "/api/conceptmaps/"
  to = "http://3.26.196.100/api/conceptmaps/:splat"
  status = 200
  force = true
# Rule 2: For CodeSystem APIs (like lookup and search)
[[redirects]]
  from = "/api/codesystem/"
  to = "http://3.26.196.100/api/codesystem/:splat"
  status = 200
  force = true
# Rule 3: For FHIR APIs
[[redirects]]
  from = "/api/fhir/*"
  to = "http://3.26.196.100/api/fhir/:splat"
  status = 200
  force = true