[build]
  command = "npm run build"
  publish = "dist" # Use "build" for Create React App

[[redirects]]
  from = "/api/conceptmaps/*"
  to = "http://3.26.95.153:8080/api/conceptmaps/:splat"
  status = 200

[[redirects]]
  from = "/api/codesystem/*"
  to = "http://3.26.95.153:8080/api/codesystem/:splat"
  status = 200

[[redirects]]
  from = "/api/fhir/*"
  to = "http://3.26.95.153:8080/api/fhir/:splat"
  status = 200