# netlify.toml
[build]
  command = "npm run build"
  publish = "dist" # Use "build" for Create React App
  functions = "netlify/functions"

# Redirect all API calls to the Netlify function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Handle SPA routing (optional - for React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200